# -*- coding: utf-8 -*-
"""classe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBg_n45-U97YWPr7aG02dKGnBQhx3nLt
"""

from classe import estudante

lis = ('Lis', 1, 7.0, 8.0, 6.0)

class estudante:
    def __init__(self, nome, matricula,  prova01, prova02, trabalho01):
      self.nome = nome
      self.matricula = matricula
      self.prova01 = prova01
      self.prova02 = prova02
      self.trabalho01 = trabalho01

    def media(self):
      print(2.5 * prova01 + 2.5 * prova02 + 2 * trabalho01 / 7)